# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"nbdev_test": "00_core.ipynb",
         "HelloSayer": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://mianhann.github.io/rater/"

git_url = "https://github.com/mianhann/rater/tree/main/"

def custom_doc_links(name): return None
